name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make build
    - name: build
      run: export TERM=xterm-256color &&chmod a+x ./build.sh && /bin/bash ./build.sh

